services:
  portfolio:
    image: ghcr.io/romainsire/portfolio-nextjs:latest
    container_name: portfolio
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.portfolio.rule=Host(`romainsire.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  traefik-public:
    external: true
